name = "endler-hugo"
description = "A Hugo theme port of endler.dev (original Zola theme)"
author = "ChenSoul"
license = "MIT"
# Minimum Hugo version
min_version = "0.110.0"

summaryLength = 3
ignoreLogs = ['warning-goldmark-raw-html']

# Pagination
[pagination]
  pagerSize = 10

[permalinks]
  posts="/posts/:year/:month/:day/:slug/"
  categories="/categories/:slug/"
  tags="/tags/:slug/"
  pages="/:slug/"

[params]
  author = "Your Name"
  description = "Your site description"

[params.social]
  mastodon = "example"  # without full URL
  github = "example"
  twitter = "example"

[params.remark42]
  enabled = true
  host = "https://remark42.example.com"
  site = "remark"
  locale = "en"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"  # generates rss.xml instead of index.xml