baseURL = "https://example.com"
languageCode = "zh-cn"
title = "Endler Hugo Theme"
theme = "endler-hugo"

[pagination]
  pagerSize = 5

[params]
  author = "Author"
  description = "A Hugo theme port of endler.dev (original Zola theme)"
  mastodon = "example"
  twitter = "example"
  github = "example"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



